title: 
description: "PhD student in High Energy Nuclear Physics"
author: 
email: 
github_username: Physicistdana

# Built-in Jekyll theme (simple + nice)
theme: jekyll-theme-cayman

# Enable kramdown + MathJax for equations
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Navbar links
# (Cayman shows these as buttons near the top)
show_downloads: false
