title: Dana Abdallah
description: "PhD student in High Energy Nuclear Physics"
theme: jekyll-theme-cayman   # you can also try jekyll-theme-slate

# Add navigation tabs (buttons)
show_downloads: false
navigation:
  - title: "Home"
    url: /
  - title: "Teaching"
    url: /teaching/
  - title: "Blog"
    url: /blog/
  - title: "CV"
    url: /cv/CV.pdf
